spring:
  application:
    name: internet-banking-fund-transfer-service

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

management:
  info:
    env:
      enabled: true

  endpoints:
    web:
      exposure:
        include: '*'

info:
  application:
    name: ${spring.application.name}
    description: Very cool Spring Boot application
    version: '@project.version@'
    spring-cloud-version: '@spring-cloud.version@'
    spring-boot-version: '@project.parent.version@'